# Generated by Django 5.0.4 on 2024-04-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('status_completed', models.BooleanField(default=False, verbose_name='Status da tarefa')),
                ('voluntary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Voluntário Responsável')),
                ('volunteers', models.ManyToManyField(blank=True, related_name='volunteers', to=settings.AUTH_USER_MODEL, verbose_name='Voluntários envolvidos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
