# Generated by Django 5.0.4 on 2024-04-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prevision_hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário previsto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista'),
        ),
    ]
