# Generated by Django 5.0.4 on 2024-04-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0003_task_detais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='detais',
            new_name='details',
        ),
    ]
