# Generated by Django 5.0.4 on 2024-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0004_rename_detais_task_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
    ]
